[build]
build-std = false
default-target = "x86_64-unknown-linux-gnu"

[target.x86_64-unknown-linux-gnu]
pre-build = ["dpkg --add-architecture $CROSS_DEB_ARCH && apt-get update && apt-get install --assume-yes libssl-dev:$CROSS_DEB_ARCH && curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && apt-get install nodejs"]